// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceResultsApi.Data;

#nullable disable

namespace RaceResultsApi.Migrations
{
    [DbContext(typeof(RaceDbContext))]
    partial class RaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaceResultsApi.Models.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorseId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HorseId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("RaceResultsApi.Models.Jockey", b =>
                {
                    b.Property<int>("JockeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JockeyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JockeyId");

                    b.ToTable("Jockeys");
                });

            modelBuilder.Entity("RaceResultsApi.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RaceDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("RaceTime")
                        .HasColumnType("time");

                    b.Property<string>("Racecourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaceId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RaceResultsApi.Models.RaceNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceResultId")
                        .HasColumnType("int");

                    b.HasKey("NoteId");

                    b.HasIndex("RaceResultId");

                    b.ToTable("RaceNotes");
                });

            modelBuilder.Entity("RaceResultsApi.Models.RaceResult", b =>
                {
                    b.Property<int>("RaceResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceResultId"));

                    b.Property<decimal?>("DistanceBeaten")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FinishingPosition")
                        .HasColumnType("int");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TimeBeaten")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("RaceResultId");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TrainerId");

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("RaceResultsApi.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("RaceResultsApi.Models.RaceNote", b =>
                {
                    b.HasOne("RaceResultsApi.Models.RaceResult", "RaceResult")
                        .WithMany("Notes")
                        .HasForeignKey("RaceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceResult");
                });

            modelBuilder.Entity("RaceResultsApi.Models.RaceResult", b =>
                {
                    b.HasOne("RaceResultsApi.Models.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceResultsApi.Models.Jockey", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceResultsApi.Models.Race", "Race")
                        .WithMany("Results")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceResultsApi.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Race");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("RaceResultsApi.Models.Race", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("RaceResultsApi.Models.RaceResult", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
